config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :entries
  root to: 'entries#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
# frozen_string_literal: true

class Entry < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
# frozen_string_literal: true

class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries or /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1 or /entries/1.json
  def show
     @entry = Entry.find(params[:id])
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
     @entry = Entry.find(params[:id])
  end

  # POST /entries or /entries.json
  def create
    @entry = Entry.new(entry_params)

    if @entry.save
      redirect_to entry_path(@entry), notice: 'Entry was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    if @entry.update(entry_params)
      redirect_to entry_path(@entry), notice: 'Entry was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    @entry.destroy  
    redirect_to root_path, notice: 'Entry was successfully destroyed'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_entry
    @entry = Entry.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def entry_params
    params.require(:entry).permit(:meal_type, :calories, :proteins, :carbohydrates, :fats)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/entries_helper.rb
# frozen_string_literal: true

module EntriesHelper
end

app/views/entries/_form.html.erb
<%= form_with(model: entry) do |form| %>
  <% if entry.errors.any? %>
    <div class="message is-danger">
      <div class="message-header">
        <p><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</p>
      </div>

      <div class="message-body">
        <ul>
          <% entry.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :meal_type, class: "label" %>
    <%= form.text_field :meal_type, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :calories, class: "label" %>
    <%= form.number_field :calories, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :proteins, class: "label" %>
    <%= form.number_field :proteins, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :carbohydrates, class: "label" %>
    <%= form.number_field :carbohydrates, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :fats, class: "label" %>
    <%= form.number_field :fats, class: "input" %>
  </div>

  <div class="actions">
    <%= form.submit class: "button is-success" %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<div class="columns is-centered mt-2">
  <div class="column is-one-third">
    <h1 class="is-size-2 has-text-weight-bold mb-2">
      Editing entry
    </h1>
    <%= render "form", entry: @entry %>
  </div>
</div>

app/views/entries/index.html.erb
<% content_for :title do %>
  Foodmenu &ndash; <%= Time.now.strftime("%d of %B, %Y") %>
<% end %>

<div class="columns mt-4 is-centered is-multiline">
  <% @entries.each do |entry| %>
    <div class="column is-one-quarter-desktop is-one-third-tablet is-two-thirds-mobile">
      <div class="card">
        <div class="card-header">
          <p class="card-header-title">
            <%= entry.meal_type %>
          </p>
        </div>
        <div class="card-content">
          <div class="content">
            <p>
              <span class="has-text-weight-bold">Calories: <%= entry.calories %>Kcal</span>
            </p>
            <p>
              <span class="has-text-weight-bold">Proteins: <%= entry.proteins %>g</span>
            </p>
            <p>
              <span class="has-text-weight-bold">Carbohydrates: <%= entry.carbohydrates %>g</span>
            </p>
            <p>
              <span class="has-text-weight-bold">Fats: <%= entry.fats %>g</span>
            </p>
            <p class="italic">Logged <%= time_ago_in_words(entry.created_at) %> ago</p>
          </div>
        </div>
        <div class="card-footer">
          <%= link_to "Show", entry, class: "card-footer-item" %>
          <%= link_to "Edit", edit_entry_path(entry), class: "card-footer-item" %>
          <%= link_to "Destroy", entry, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "card-footer-item" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/entries/new.html.erb
<div class="columns is-centered mt-2">
  <div class="column is-one-third">
    <h1 class="is-size-2 has-text-weight-bold mb-2">
      New entry
    </h1>
    <%= render "form", entry: @entry %>
  </div>
</div>

app/views/entries/show.html.erb
<% content_for :title do %>
  <%= @entry.meal_type %> &ndash; <%= Time.now.strftime("%d of %B, %Y") %>
<% end %>

<div class="columns mt-6 is-centered mr-4 ml-4">
  <div class="column is-two-fifths">
    <nav class="panel is-link">
      <p class="panel-heading">
        <%= @entry.meal_type %>
      </p>
      <div class="panel-block">
        Calories: <%= @entry.calories %>Kcal
      </div>
      <div class="panel-block">
        Proteins: <%= @entry.proteins %>g</span>
      </div>
      <div class="panel-block">
        Carbohydrates: <%= @entry.carbohydrates %>g
      </div>
      <div class="panel-block">
        Fats: <%= @entry.fats %>g
      </div>
    </nav>
    <div class="columns is-mobile">
      <div class="column is-two-thirds">
        <%= link_to "Edit", edit_entry_path(@entry), class: "button is-gray" %>
        <%= link_to "Delete", entry_path(@entry), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "button is-gray" %>
      </div>
      <div class="column">
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foodmenu</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/header" %>

    <% if notice.present? %>
      <div class="notification is-link is-light"><%= notice %></div>
    <% end %>

    
    <% if alert.present? %>
      <div class="notification is-danger is-light"><%= alert %></div>
    <% end %>
    
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_header.html.erb
<section class="hero is-link is-small">
  <!-- Hero head: will stick at the top -->
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <a class="navbar-item">
            <%= link_to root_path, class: "navbar-item" do  %>
              <svg fill="#ffffff" xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 32 32"><title>rice</title><g stroke-linecap="square" stroke-linejoin="miter" stroke-width="2" fill="none" stroke="currentColor" stroke-miterlimit="10"><path d="M10.65,30h10.7A14.991,14.991,0,0,0,31,16H1A14.991,14.991,0,0,0,10.65,30Z"></path><path d="M29,12a3.993,3.993,0,0,0-7.243-2.326A3.943,3.943,0,0,0,16.1,7.5,3.967,3.967,0,0,0,9.239,8.685,4,4,0,0,0,3,12"></path><line x1="26.764" y1="8.413" x2="31" y2="1" stroke-linecap="butt"></line> <line x1="23.517" y1="8.289" x2="25" y2="2" stroke-linecap="butt"></line> <circle cx="6" cy="4" r="1" fill="currentColor" stroke="none"></circle> <circle cx="17" cy="2" r="1" fill="currentColor" stroke="none"></circle></g></svg>
              <span class="has-text-weight-bold is-size-4 ml-2">Foodmenu</span>
            <% end %>
          </a>
          <span class="navbar-burger" data-target="navbarMenuHeroA">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarMenuHeroA" class="navbar-menu">
          <div class="navbar-end navbar-item">
            <%= link_to "Create new entry", new_entry_path, class: "button is-success"  %>
          </div>
        </div>
      </div>
    </nav>
  </div>
  <!-- Hero content: will be in the middle -->
  <div class="hero-body">
    <div class="container has-text-centered">
      <p class="title">
        <% if content_for :title %>
          <%= yield :title %>  
        <% else %>
          Foodmenu
        <% end %>
      </p>
    </div>
  </div>
</section>